### ISSUE TITLE
Add .biml extension

### ISSUE THREAD

**Issue by williamrschmidt** [zbecknell/t4-support#3]
Hi - I work with BIML files (https://www.varigence.com/Biml), which are basically a flavor of T4 file, and I find that if I change the .biml extension on those files to .tt extensions, your syntax highlighter seems to work.

There is no specific .biml file syntax highlighting extension out there for VS Code, so I wonder if you could add the .biml extension as a supported extension for your t4-support project. You might find that you get some more downloads from people who work with BIML and would like to use VS Code.

**Comment by zbecknell** [comment]
Thanks for bringing that to my attention, William.  It looked like an easy win, so I went ahead and made a new extension for less ambiguity: 

https://marketplace.visualstudio.com/items?itemName=zbecknell.biml-support

As you can see, I also made sure it used XML highlighting by default for a bit better experience.

**Comment by williamrschmidt** [comment]
Wow – that’s terrific. Thanks very much!

________________________________

**Comment by williamrschmidt** [comment]
Zachary,

I just wrote an email about the extension to Cathrine Wilhelmsen cathrine.wilhelmsen@gmail.com<mailto:cathrine.wilhelmsen@gmail.com>, who is a trainer and general expert on BIML. Just thought I’d pass what I wrote along to you too. Were you to ever need any information about the preferences or needs of BIML developers, I am pretty sure Cathrine would be a good person to contact.

--Text of message to Cathrine—

Cathrine,

I attended one of your daylong workshops a few years ago and have read a lot of your online posts, so I figured you might be a good person to tell about this in case you want to pass it along.

I’ve had trouble frequently with the BIML Express editor, which for me at least, using VS 2017, crashes a lot or does even worse things, like seeming to work for a long stretch of editing, then not actually saving any of the work when I click save (and giving me no indication that anything is wrong).

So I got into the habit of working on my BIML files using Visual Studio Code, which because there is no BIML add-in, doesn’t have these issues. But the problem there was that there was no awareness of .biml as a file extension, so the text was all uniformly white, with no easy way to visually scan and find comments, XML, c# code, etc.

I then did the experiment of changing the .biml extension to .tt, and found that a VS Code extension for T4 template files did a great job of handling the BIML syntax highlighting too. So I contacted the developer of that T4 syntax highlighting extension and asked if he could adapt what he had done to include .biml files too.

He did, and there is now the first-ever (as far as I can tell) Visual Studio Code extension to provide syntax highlighting for BIML files.

I now use this all the time, because the problems with the BIML Express VS add-in have not gone away. To make the workflow easier back and forth between VS 2017 and VS Code, I installed a VS 2017 extension that adds an “Open in VS Code” choice to my VS 2017 context menu. That way, while working on a BIML solution in VS 2017, when I need to edit a .biml file, I just right-click on it and use the context menu to open the file in the VS Code editor.

Anyway, I highly recommend this VS Code extension to any other BIML developers who would like to be able to use VS Code for editing .biml files.

Regards,

William Schmidt
Chicago, IL

________________________________
From: William Schmidt
Sent: Friday, July 19, 2019 8:53:49 AM
To: zbecknell/t4-support <reply@reply.github.com>; zbecknell/t4-support <t4-support@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [zbecknell/t4-support] Add .biml extension (#3)

Wow – that’s terrific. Thanks very much!

________________________________

**Comment by zbecknell** [comment]
I appreciate you passing that along and I'm glad you're getting good use from these extensions.  I'll let you know that I also submitted the Biml icon to vscode-icons for inclusion in that library (highly recommend it if you don't already use that extension): https://github.com/vscode-icons/vscode-icons/issues/2142

Also, if you'd like any specific tweaks to the Biml extension, please feel free to request them here: https://github.com/zbecknell/biml-support

I don't have a ton of experience with VS extensions, but one quick thing I could do is snippets, if that's something you'd be interested in having in the extension.

**Comment by williamrschmidt** [comment]
Hey Zachary,

No tweaks I can think of right at the moment. I did get an email from Cathrine Wilhelmsen saying thanks and that she would be writing a blog post about the extension.

Regards,

Bill Schmidt

________________________________

**Comment by williamrschmidt** [comment]
Zachary,

In case you weren’t already aware, Cathrine Wilhelmsen has published a blog post about your extension.

https://www.cathrinewilhelmsen.net/2019/08/01/biml-syntax-highlighting-visual-studio-code/#more-8157

Cheers,

Bill Schmidt

________________________________
From: William Schmidt
Sent: Wednesday, July 31, 2019 4:52:09 PM
To: zbecknell/t4-support <reply@reply.github.com>; zbecknell/t4-support <t4-support@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [zbecknell/t4-support] Add .biml extension (#3)

Hey Zachary,

No tweaks I can think of right at the moment. I did get an email from Cathrine Wilhelmsen saying thanks and that she would be writing a blog post about the extension.

Regards,

Bill Schmidt

________________________________

**Comment by zbecknell** [comment]
Excellent, William!  Thanks again for forwarding this on and I hope the Biml community has a bit more pleasant time working with their Biml files!
