### ISSUE TITLE
Background color switches when 2 blocks follow each other

### ISSUE THREAD

**Issue by TristanPct** [zbecknell/t4-support#5]
Hi, and thanks for this extension!

I discovered that if 2 blocks follow each other the background color (used to highlight C# code) is inverted on the rest of the file.

![demo](https://user-images.githubusercontent.com/5139018/81932199-b2edbf00-95eb-11ea-97b1-9a4651f9ce89.png)

With a space between the 2 blocks everything goes back to normal.

Problem seems to come from: https://github.com/zbecknell/t4-support/blob/29128433b219f222f0449b1a0ffac6a25e217d00/src/extension.ts#L53

When I hover between the 2 blocks I have `T4 Bracket #><#=`.

**Comment by zbecknell** [comment]
Thanks for bringing this to my attention, Tristan!  I'll have a look soon and get it worked out.

**Comment by zbecknell** [comment]
Version 0.4.4 should show up for you soon with the fix.  It was as simple as adding the closing bracket to a new match group.  Good catch!
